"use client"

import { useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import { AdminAuth } from "@/lib/admin-auth"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { ArrowLeft, Book, Sparkles, CheckCircle, Clock, FileText } from "lucide-react"

export default function ContentManagementPage() {
  const router = useRouter()
  const [pendingCount, setPendingCount] = useState(0)

  useEffect(() => {
    if (!AdminAuth.isAuthenticated() || !AdminAuth.hasPermission("content_management")) {
      router.push("/admin")
    }

    const pending = localStorage.getItem("ai_pending_content")
    if (pending) {
      const items = JSON.parse(pending)
      setPendingCount(items.length)
    }
  }, [router])

  const contentSections = [
    {
      id: "verses",
      title: "Bible Verses",
      description: "Add and edit verses for all age groups",
      icon: Book,
      badge: null,
      href: "/admin/content/verses",
      color: "blue",
    },
    {
      id: "ai-review",
      title: "AI Content Review",
      description: "Review and approve AI-generated content",
      icon: Sparkles,
      badge: pendingCount > 0 ? `${pendingCount} pending` : null,
      href: "/admin/content/ai-review",
      color: "purple",
    },
    {
      id: "published",
      title: "Published Content",
      description: "View and manage live content",
      icon: CheckCircle,
      badge: null,
      href: "/admin/content/published",
      color: "green",
    },
  ]

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white border-b sticky top-0 z-10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center gap-4 h-16">
            <Button variant="ghost" size="sm" onClick={() => router.push("/admin/dashboard")}>
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back
            </Button>
            <div className="flex-1">
              <h1 className="text-xl font-bold text-gray-900">Content Management</h1>
              <p className="text-xs text-gray-500">Manage Bible verses and AI-generated content</p>
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          {contentSections.map((section) => {
            const Icon = section.icon
            return (
              <Card
                key={section.id}
                className="cursor-pointer hover:shadow-lg transition-shadow"
                onClick={() => router.push(section.href)}
              >
                <CardHeader>
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <div className="flex items-center gap-2">
                        <CardTitle className="text-lg">{section.title}</CardTitle>
                        {section.badge && (
                          <Badge variant="secondary" className="bg-orange-100 text-orange-700">
                            {section.badge}
                          </Badge>
                        )}
                      </div>
                      <CardDescription className="mt-1">{section.description}</CardDescription>
                    </div>
                    <div
                      className={`w-12 h-12 bg-${section.color}-50 rounded-lg flex items-center justify-center text-${section.color}-600`}
                    >
                      <Icon className="w-6 h-6" />
                    </div>
                  </div>
                </CardHeader>
                <CardContent>
                  <Button variant="ghost" size="sm" className="w-full">
                    Manage →
                  </Button>
                </CardContent>
              </Card>
            )
          })}
        </div>

        {/* AI Content Info Card */}
        <Card className="bg-gradient-to-br from-purple-50 to-blue-50 border-purple-200">
          <CardHeader>
            <div className="flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-purple-600" />
              <CardTitle>AI-Powered Content Generation</CardTitle>
            </div>
            <CardDescription>
              Daily devotionals, prayers, verse explanations, and quiz questions are automatically generated by AI
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            <div className="flex items-start gap-3 text-sm">
              <Clock className="w-4 h-4 text-purple-600 mt-0.5" />
              <div>
                <p className="font-medium text-gray-900">Review Queue</p>
                <p className="text-gray-600 text-xs">
                  AI generates content based on Bible verses. Review and approve before publishing.
                </p>
              </div>
            </div>
            <div className="flex items-start gap-3 text-sm">
              <CheckCircle className="w-4 h-4 text-green-600 mt-0.5" />
              <div>
                <p className="font-medium text-gray-900">Published Content</p>
                <p className="text-gray-600 text-xs">Approved content is live and visible to all users in the app.</p>
              </div>
            </div>
            <div className="flex items-start gap-3 text-sm">
              <FileText className="w-4 h-4 text-blue-600 mt-0.5" />
              <div>
                <p className="font-medium text-gray-900">Bible Verses</p>
                <p className="text-gray-600 text-xs">
                  Manually manage verses which serve as the foundation for AI-generated content.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </main>
    </div>
  )
}
